# Master Connection (Writes)
spring.datasource.master.jdbc-url=jdbc:mysql://localhost:3310/prototype
spring.datasource.master.username=root
spring.datasource.master.password=root
spring.datasource.master.driver-class-name=com.mysql.cj.jdbc.Driver

# Replica Connection (Reads)
spring.datasource.replica.jdbc-url=jdbc:mysql://localhost:3311/prototype
spring.datasource.replica.username=root
spring.datasource.replica.password=root
spring.datasource.replica.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true